/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/invitations': typeof InvitationsRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/users': typeof UsersRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/invitations': typeof InvitationsRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/users': typeof UsersRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/invitations': typeof InvitationsRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/users': typeof UsersRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/events'
    | '/invitations'
    | '/queue'
    | '/register'
    | '/review'
    | '/scan'
    | '/settings'
    | '/status'
    | '/users'
    | '/auth/$pathname'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/events'
    | '/invitations'
    | '/queue'
    | '/register'
    | '/review'
    | '/scan'
    | '/settings'
    | '/status'
    | '/users'
    | '/auth/$pathname'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/events'
    | '/invitations'
    | '/queue'
    | '/register'
    | '/review'
    | '/scan'
    | '/settings'
    | '/status'
    | '/users'
    | '/auth/$pathname'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  InvitationsRoute: typeof InvitationsRoute
  QueueRoute: typeof QueueRoute
  RegisterRoute: typeof RegisterRoute
  ReviewRoute: typeof ReviewRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  UsersRoute: typeof UsersRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  CompaniesRoute: CompaniesRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  InvitationsRoute: InvitationsRoute,
  QueueRoute: QueueRoute,
  RegisterRoute: RegisterRoute,
  ReviewRoute: ReviewRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  UsersRoute: UsersRoute,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
