/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventManagementRouteImport } from './routes/event-management'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupUserRouteImport } from './routes/signup.user'
import { Route as SignupSuperAdminRouteImport } from './routes/signup.super-admin'
import { Route as SignupAdminRouteImport } from './routes/signup.admin'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventManagementRoute = EventManagementRouteImport.update({
  id: '/event-management',
  path: '/event-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupUserRoute = SignupUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => SignupRoute,
} as any)
const SignupSuperAdminRoute = SignupSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => SignupRoute,
} as any)
const SignupAdminRoute = SignupAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SignupRoute,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/event-management': typeof EventManagementRoute
  '/events': typeof EventsRoute
  '/invitations': typeof InvitationsRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/signup/admin': typeof SignupAdminRoute
  '/signup/super-admin': typeof SignupSuperAdminRoute
  '/signup/user': typeof SignupUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/event-management': typeof EventManagementRoute
  '/events': typeof EventsRoute
  '/invitations': typeof InvitationsRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/signup/admin': typeof SignupAdminRoute
  '/signup/super-admin': typeof SignupSuperAdminRoute
  '/signup/user': typeof SignupUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/event-management': typeof EventManagementRoute
  '/events': typeof EventsRoute
  '/invitations': typeof InvitationsRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/users': typeof UsersRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/signup/admin': typeof SignupAdminRoute
  '/signup/super-admin': typeof SignupSuperAdminRoute
  '/signup/user': typeof SignupUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/event-management'
    | '/events'
    | '/invitations'
    | '/queue'
    | '/register'
    | '/review'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/status'
    | '/subscription'
    | '/users'
    | '/auth/$pathname'
    | '/signup/admin'
    | '/signup/super-admin'
    | '/signup/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/event-management'
    | '/events'
    | '/invitations'
    | '/queue'
    | '/register'
    | '/review'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/status'
    | '/subscription'
    | '/users'
    | '/auth/$pathname'
    | '/signup/admin'
    | '/signup/super-admin'
    | '/signup/user'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/event-management'
    | '/events'
    | '/invitations'
    | '/queue'
    | '/register'
    | '/review'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/status'
    | '/subscription'
    | '/users'
    | '/auth/$pathname'
    | '/signup/admin'
    | '/signup/super-admin'
    | '/signup/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  EventManagementRoute: typeof EventManagementRoute
  EventsRoute: typeof EventsRoute
  InvitationsRoute: typeof InvitationsRoute
  QueueRoute: typeof QueueRoute
  RegisterRoute: typeof RegisterRoute
  ReviewRoute: typeof ReviewRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRouteWithChildren
  StatusRoute: typeof StatusRoute
  SubscriptionRoute: typeof SubscriptionRoute
  UsersRoute: typeof UsersRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-management': {
      id: '/event-management'
      path: '/event-management'
      fullPath: '/event-management'
      preLoaderRoute: typeof EventManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/user': {
      id: '/signup/user'
      path: '/user'
      fullPath: '/signup/user'
      preLoaderRoute: typeof SignupUserRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/super-admin': {
      id: '/signup/super-admin'
      path: '/super-admin'
      fullPath: '/signup/super-admin'
      preLoaderRoute: typeof SignupSuperAdminRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/admin': {
      id: '/signup/admin'
      path: '/admin'
      fullPath: '/signup/admin'
      preLoaderRoute: typeof SignupAdminRouteImport
      parentRoute: typeof SignupRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignupRouteChildren {
  SignupAdminRoute: typeof SignupAdminRoute
  SignupSuperAdminRoute: typeof SignupSuperAdminRoute
  SignupUserRoute: typeof SignupUserRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupAdminRoute: SignupAdminRoute,
  SignupSuperAdminRoute: SignupSuperAdminRoute,
  SignupUserRoute: SignupUserRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CompaniesRoute: CompaniesRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  EventManagementRoute: EventManagementRoute,
  EventsRoute: EventsRoute,
  InvitationsRoute: InvitationsRoute,
  QueueRoute: QueueRoute,
  RegisterRoute: RegisterRoute,
  ReviewRoute: ReviewRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRouteWithChildren,
  StatusRoute: StatusRoute,
  SubscriptionRoute: SubscriptionRoute,
  UsersRoute: UsersRoute,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
